### ISSUE TITLE
Pushback tug beacon comes through cockpit

### ISSUE THREAD

**Issue by GlitchedYT** [wpine215/msfs-a320neo#95] opened 2020-08-26 02:09 UTC
pushback tug beacon illuminates on the side of the walls next to the foot pedals as well as above the PFD and NFD display brightness knobs.

Video: https://imgur.com/ksOAcyT

**Comment by EntroPiGames** [comment] 2020-08-26 08:15
This is probably caused by shadows being disabled for the pushback tug's light. The same issue causes the cockpit to be illuminated when the nose wheel light is set to taxi.

Not sure if this can be fixed without access to the rendering API in the game engine. I'm sure Asobo is aware of the issue though.

**Comment by wpine215** [comment] 2020-08-28 06:56
Not an issue that can be fixed by modifying this aircraft.

**Closed by wpine215** 2020-08-28 06:56 UTC
Labels: enhancement
