### ISSUE TITLE
[BUG] APU page doesn't work if you start the APU, then shut it off before it's available

### ISSUE THREAD

**Issue by mythicfci** [wpine215/msfs-a320neo#353] opened 2020-09-03 13:26 UTC
**Describe the bug**
The APU page doesn't work if you start the APU, then shut it off before it's available

**To Reproduce**
1. Start the APU normally (press the APU MASTER switch, then the APU START switch once available)
2. Before the APU fully starts up (i.e. before AVAIL shows up on the MFD and the APU MASTER button), shut down the APU by pressing the APU MASTER switch again.
3. Try starting the APU again in the same way as step 1.

**Expected behavior**
The APU should start up as normal, with the APU page showing the APU spooling up. However, what happens is that the APU page remains static and doesn't show the spool-up. However, the APU itself still seems to start up normally.

**Additional context**
I'm running the latest dev build on MSFS v1.17.14.0, i.e. the latest patch.

**Comment by UncleClapton** [comment] 2020-09-04 02:23
In what way does the apu page stop working?

Unable to reproduce after the fixes made with #347 and #348 (not yet merged).

**Comment by mythicfci** [comment] 2020-09-04 03:47
@UncleClapton No matter how many times you press the APU MASTER and APU START switches, the APU page remains static.

**Comment by AdenFlorian** [comment] 2020-09-04 04:33
@mythicfci when did you last retest it? And are you testing on the dev branch or one of the release candidates?

**Comment by UncleClapton** [comment] 2020-09-04 04:43
try downloading the latest dev build please. there have been significant changes made to the APU in the last day.

**Comment by mythicfci** [comment] 2020-09-04 07:12
Just tested, I can confirm that on the latest dev build `1cedd50` this bug seems to be fixed. Thanks so much y'all! @UncleClapton @AdenFlorian

**Comment by Coralec** [comment] 2020-09-04 07:16
Tested on latest dev build (1cedd50) and working properly.

**Closed** 2020-09-04 07:50 UTC
Labels: bug, bug-a32nx, ready to test
