### ISSUE TITLE
Cockpit completly bugged on last dev branch update

### ISSUE THREAD

**Issue by vref-simulations** [wpine215/msfs-a320neo#276] opened 2020-08-31 11:27 UTC
![asdasda](https://user-images.githubusercontent.com/67702788/91715355-d66d5300-eb63-11ea-9f5c-88ac1e523069.png)

**Comment by michaeldiguiseppi** [comment] 2020-08-31 15:40
This should be resolved in the latest dev branch.

**Comment by Curtis-VL** [comment] 2020-09-01 15:32
@vref-simulations Please close this issue is the issue is resolved! 👍

**Closed** 2020-09-02 17:05 UTC
Labels: awaiting feedback
